### ISSUE TITLE
Can't get the token...

### ISSUE THREAD

**Issue by Hershco** [nitaybz/homebridge-tami4#12]
Hi,

I'm using the latest Homebrige version on Ubuntu on Hyper-V on Windows 11, I'm really noob at this.
No matter what i'm doing I can't get past the "enter your phone number" part, it's started with "chromium isn't installed" and now this is what i'm receiving when trying to extract it from terminal:

This script is using the browser to bypass captcha, it will now search for an installed browser
Running on unknown device, searching for Chromium path...
found path: /usr/bin/chromium-browser
Error: Evaluation failed: ReferenceError: grecaptcha is not defined
    at __puppeteer_evaluation_script__:3:3
    at ExecutionContext._evaluateInternal (/var/lib/homebridge/node_modules/homebridge-tami4/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/var/lib/homebridge/node_modules/homebridge-tami4/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async getCaptcha (/var/lib/homebridge/node_modules/homebridge-tami4/bin/cli.js:120:21)
    at async /var/lib/homebridge/node_modules/homebridge-tami4/bin/cli.js:29:16
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Evaluation failed: ReferenceError: grecaptcha is not defined
    at __puppeteer_evaluation_script__:3:3
    at ExecutionContext._evaluateInternal (/var/lib/homebridge/node_modules/homebridge-tami4/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (/var/lib/homebridge/node_modules/homebridge-tami4/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async getCaptcha (/var/lib/homebridge/node_modules/homebridge-tami4/bin/cli.js:120:21)
    at async /var/lib/homebridge/node_modules/homebridge-tami4/bin/cli.js:29:16
    

I have no idea what else I should do, I tried to install puppeteer on the homebridge image and I tried to do what arthurzaf said here: https://github.com/nitaybz/homebridge-tami4/issues/3#issuecomment-1106566555

Nothing worked, I'd very much appreciate the help, thanks.
    
![image](https://github.com/nitaybz/homebridge-tami4/assets/141374271/57bc04ac-a6cb-4e9b-903e-158f5681173e)

**Comment by johnbenz13** [comment]
Hi, I'm getting the same error. Did you manage to find a solution?

**Comment by Hershco** [comment]
> Hi, I'm getting the same error. Did you manage to find a solution?

What I ended up doing was download the Tami4 app for my iPhone, and an app called "HTTP Catcher", I paid a one time purchase for a permium access in the HTTP catcher app, something like 5$.
The app records web traffic and what I did was:

1. I opened the HTTP Catcher app, then the Tami4 app.
2. In the Tami4 app I signed out of my account
3. went back to the HTTP Catcher app, start recording
4. went back to the Tami4 app, logged back into my user
5. went back to the HTTP catcher app, stopped the recording
6. in the search bar searched for "OTP" or "Token", can't quite remember, and there I found a few sequences including this word, each one had a token.
7. I tried each one untill it finally worked.

I hope it helps!

**Comment by johnbenz13** [comment]
Thanks for the great help 🙏

**Comment by talavital2** [comment]
> > Hi, I'm getting the same error. Did you manage to find a solution?
> 
> What I ended up doing was download the Tami4 app for my iPhone, and an app called "HTTP Catcher", I paid a one time purchase for a permium access in the HTTP catcher app, something like 5$. The app records web traffic and what I did was:
> 
> 1. I opened the HTTP Catcher app, then the Tami4 app.
> 2. In the Tami4 app I signed out of my account
> 3. went back to the HTTP Catcher app, start recording
> 4. went back to the Tami4 app, logged back into my user
> 5. went back to the HTTP catcher app, stopped the recording
> 6. in the search bar searched for "OTP" or "Token", can't quite remember, and there I found a few sequences including this word, each one had a token.
> 7. I tried each one untill it finally worked.
> 
> I hope it helps!


Hi, 

Tried that but can't see the token in the catcher app.

**Comment by Hershco** [comment]
> > > Hi, I'm getting the same error. Did you manage to find a solution?
> > 
> > 
> > What I ended up doing was download the Tami4 app for my iPhone, and an app called "HTTP Catcher", I paid a one time purchase for a permium access in the HTTP catcher app, something like 5$. The app records web traffic and what I did was:
> > 
> > 1. I opened the HTTP Catcher app, then the Tami4 app.
> > 2. In the Tami4 app I signed out of my account
> > 3. went back to the HTTP Catcher app, start recording
> > 4. went back to the Tami4 app, logged back into my user
> > 5. went back to the HTTP catcher app, stopped the recording
> > 6. in the search bar searched for "OTP" or "Token", can't quite remember, and there I found a few sequences including this word, each one had a token.
> > 7. I tried each one untill it finally worked.
> > 
> > I hope it helps!
> 
> Hi,
> 
> Tried that but can't see the token in the catcher app.

Try to change the section to headers, and when you choose a sequence try to find the token in the section “response”. 

It’s suppose to be somewhere there I’m not 100% remember.

**Comment by johnbenz13** [comment]
> > > Hi, I'm getting the same error. Did you manage to find a solution?
> > 
> > 
> > What I ended up doing was download the Tami4 app for my iPhone, and an app called "HTTP Catcher", I paid a one time purchase for a permium access in the HTTP catcher app, something like 5$. The app records web traffic and what I did was:
> > 
> > 1. I opened the HTTP Catcher app, then the Tami4 app.
> > 2. In the Tami4 app I signed out of my account
> > 3. went back to the HTTP Catcher app, start recording
> > 4. went back to the Tami4 app, logged back into my user
> > 5. went back to the HTTP catcher app, stopped the recording
> > 6. in the search bar searched for "OTP" or "Token", can't quite remember, and there I found a few sequences including this word, each one had a token.
> > 7. I tried each one untill it finally worked.
> > 
> > I hope it helps!
> 
> Hi,
> 
> Tried that but can't see the token in the catcher app.

You also need to activate HTTPS and look for the URL `swelcustomers.strauss-water.com`

**Comment by nitaybz** [comment]
Sorry for the long delay. This was a problem with the old Chromium / Puppeteer based token extraction, which v1.3.0 (November 2024) replaced with a Homebridge-UI based flow. No more grecaptcha references and no more Chromium dependency, the reCAPTCHA and OTP flow now run in your browser via the plugin settings page.

Closing as obsolete. If you are on a current version and the in-UI flow does not work for you, please open a fresh issue with the network tab output from the plugin settings page so I can see what the Strauss endpoint is rejecting.
