### ISSUE TITLE
Plugin doesn't add accessory

### ISSUE THREAD

**Issue by galzil** [nitaybz/homebridge-tami4#2]
Registration is working now but homebridge crashes

`[Tami4] Creating New Tami4 Accessory ()
AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:421:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at new Thermostat (/usr/local/lib/node_modules/homebridge-tami4/homekit/device.js:33:21)
    at /usr/local/lib/node_modules/homebridge-tami4/tami4/syncHomeKitCache.js:6:4
    at Array.forEach (<anonymous>)
    at tami4Platform.syncHomeKitCache (/usr/local/lib/node_modules/homebridge-tami4/tami4/syncHomeKitCache.js:5:20)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-tami4/index.js:74:9)
Got SIGTERM, shutting down Homebridge...`

**Comment by galzil** [comment]
Error on V 1.0.4
`[14/03/2022, 20:05:57] [Tami4] Creating New Tami4 Accessory ()
[14/03/2022, 20:05:57] AssertionError [ERR_ASSERTION]: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:421:11)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:70:9)
    at new Tami4 (/usr/local/lib/node_modules/homebridge-tami4/homekit/device.js:34:21)
    at /usr/local/lib/node_modules/homebridge-tami4/tami4/syncHomeKitCache.js:6:4
    at Array.forEach (<anonymous>)
    at tami4Platform.syncHomeKitCache (/usr/local/lib/node_modules/homebridge-tami4/tami4/syncHomeKitCache.js:5:20)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-tami4/index.js:74:9)
[14/03/2022, 20:05:57] Got SIGTERM, shutting down Homebridge...
[14/03/2022, 20:06:02] [HB Supervisor] Homebridge Process Ended.`
