### ISSUE TITLE
Cannot pass the otp phase

### ISSUE THREAD

**Issue by ransa808** [nitaybz/homebridge-tami4#7]
Trying to run it on my hoobs machine (RPI)

hoobs@hoobs:~ $ tami4-extract 

You'll need the phone that was registered to Tami4 to get OTP password via SMS.

? Please insert the phone number registered to Tami4 (e.g. +972524001234): › +972**********
This script is using the browser to bypass captcha, it will now search for an installed browser
Running on a RPi, searching for Chromium path...
found path: /usr/bin/chromium-browser
✔ Please insert the phone number registered to Tami4 (e.g. +972524001234): … +972**********
? Please enter the OTP code received at your phone: › 7219/usr/lib/node_modules/homebridge-tami4/bin/cli.js:61
			const pass = code.match(/^\d{4}$/i)
			                  ^

TypeError: code.match is not a function
    at NumberPrompt.validate [as validator] (/usr/lib/node_modules/homebridge-tami4/bin/cli.js:61:22)
    at NumberPrompt.validate (/usr/lib/node_modules/homebridge-tami4/node_modules/prompts/lib/elements/number.js:97:28)
    at NumberPrompt.submit (/usr/lib/node_modules/homebridge-tami4/node_modules/prompts/lib/elements/number.js:106:16)
    at ReadStream.keypress (/usr/lib/node_modules/homebridge-tami4/node_modules/prompts/lib/elements/prompt.js:32:16)
    at ReadStream.emit (node:events:513:28)
    at emitKeys (node:internal/readline/utils:357:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (node:internal/readline/emitKeypressEvents:61:36)
    at ReadStream.emit (node:events:525:35)
    at addChunk (node:internal/streams/readable:315:12)

**Comment by Aransh** [comment]
Same here

**Comment by nitaybz** [comment]
Sorry for the very long delay. The terminal-based `tami4-extract` CLI was retired in v1.3.0 (November 2024) and replaced with an in-Homebridge-UI flow that handles the OTP and reCAPTCHA in the browser. No more crashes on a numeric OTP value and no more Chromium prerequisite.

Closing this as obsolete. To set up: open the Tami4 plugin's settings page in the Homebridge UI, follow the phone / OTP prompts there.
